# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['RegistrationArgs', 'Registration']

@pulumi.input_type
class RegistrationArgs:
    def __init__(__self__, *,
                 account_key_algorithm: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_ecdsa_curve: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_pem: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_rsa_bits: Optional[pulumi.Input[_builtins.int]] = None,
                 email_address: Optional[pulumi.Input[_builtins.str]] = None,
                 external_account_binding: Optional[pulumi.Input['RegistrationExternalAccountBindingArgs']] = None):
        """
        The set of arguments for constructing a Registration resource.
        """
        if account_key_algorithm is not None:
            pulumi.set(__self__, "account_key_algorithm", account_key_algorithm)
        if account_key_ecdsa_curve is not None:
            pulumi.set(__self__, "account_key_ecdsa_curve", account_key_ecdsa_curve)
        if account_key_pem is not None:
            pulumi.set(__self__, "account_key_pem", account_key_pem)
        if account_key_rsa_bits is not None:
            pulumi.set(__self__, "account_key_rsa_bits", account_key_rsa_bits)
        if email_address is not None:
            pulumi.set(__self__, "email_address", email_address)
        if external_account_binding is not None:
            pulumi.set(__self__, "external_account_binding", external_account_binding)

    @_builtins.property
    @pulumi.getter(name="accountKeyAlgorithm")
    def account_key_algorithm(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "account_key_algorithm")

    @account_key_algorithm.setter
    def account_key_algorithm(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_key_algorithm", value)

    @_builtins.property
    @pulumi.getter(name="accountKeyEcdsaCurve")
    def account_key_ecdsa_curve(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "account_key_ecdsa_curve")

    @account_key_ecdsa_curve.setter
    def account_key_ecdsa_curve(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_key_ecdsa_curve", value)

    @_builtins.property
    @pulumi.getter(name="accountKeyPem")
    def account_key_pem(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "account_key_pem")

    @account_key_pem.setter
    def account_key_pem(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_key_pem", value)

    @_builtins.property
    @pulumi.getter(name="accountKeyRsaBits")
    def account_key_rsa_bits(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "account_key_rsa_bits")

    @account_key_rsa_bits.setter
    def account_key_rsa_bits(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "account_key_rsa_bits", value)

    @_builtins.property
    @pulumi.getter(name="emailAddress")
    def email_address(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "email_address")

    @email_address.setter
    def email_address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "email_address", value)

    @_builtins.property
    @pulumi.getter(name="externalAccountBinding")
    def external_account_binding(self) -> Optional[pulumi.Input['RegistrationExternalAccountBindingArgs']]:
        return pulumi.get(self, "external_account_binding")

    @external_account_binding.setter
    def external_account_binding(self, value: Optional[pulumi.Input['RegistrationExternalAccountBindingArgs']]):
        pulumi.set(self, "external_account_binding", value)


@pulumi.input_type
class _RegistrationState:
    def __init__(__self__, *,
                 account_key_algorithm: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_ecdsa_curve: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_pem: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_rsa_bits: Optional[pulumi.Input[_builtins.int]] = None,
                 email_address: Optional[pulumi.Input[_builtins.str]] = None,
                 external_account_binding: Optional[pulumi.Input['RegistrationExternalAccountBindingArgs']] = None,
                 registration_url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Registration resources.
        """
        if account_key_algorithm is not None:
            pulumi.set(__self__, "account_key_algorithm", account_key_algorithm)
        if account_key_ecdsa_curve is not None:
            pulumi.set(__self__, "account_key_ecdsa_curve", account_key_ecdsa_curve)
        if account_key_pem is not None:
            pulumi.set(__self__, "account_key_pem", account_key_pem)
        if account_key_rsa_bits is not None:
            pulumi.set(__self__, "account_key_rsa_bits", account_key_rsa_bits)
        if email_address is not None:
            pulumi.set(__self__, "email_address", email_address)
        if external_account_binding is not None:
            pulumi.set(__self__, "external_account_binding", external_account_binding)
        if registration_url is not None:
            pulumi.set(__self__, "registration_url", registration_url)

    @_builtins.property
    @pulumi.getter(name="accountKeyAlgorithm")
    def account_key_algorithm(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "account_key_algorithm")

    @account_key_algorithm.setter
    def account_key_algorithm(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_key_algorithm", value)

    @_builtins.property
    @pulumi.getter(name="accountKeyEcdsaCurve")
    def account_key_ecdsa_curve(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "account_key_ecdsa_curve")

    @account_key_ecdsa_curve.setter
    def account_key_ecdsa_curve(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_key_ecdsa_curve", value)

    @_builtins.property
    @pulumi.getter(name="accountKeyPem")
    def account_key_pem(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "account_key_pem")

    @account_key_pem.setter
    def account_key_pem(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_key_pem", value)

    @_builtins.property
    @pulumi.getter(name="accountKeyRsaBits")
    def account_key_rsa_bits(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "account_key_rsa_bits")

    @account_key_rsa_bits.setter
    def account_key_rsa_bits(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "account_key_rsa_bits", value)

    @_builtins.property
    @pulumi.getter(name="emailAddress")
    def email_address(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "email_address")

    @email_address.setter
    def email_address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "email_address", value)

    @_builtins.property
    @pulumi.getter(name="externalAccountBinding")
    def external_account_binding(self) -> Optional[pulumi.Input['RegistrationExternalAccountBindingArgs']]:
        return pulumi.get(self, "external_account_binding")

    @external_account_binding.setter
    def external_account_binding(self, value: Optional[pulumi.Input['RegistrationExternalAccountBindingArgs']]):
        pulumi.set(self, "external_account_binding", value)

    @_builtins.property
    @pulumi.getter(name="registrationUrl")
    def registration_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "registration_url")

    @registration_url.setter
    def registration_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "registration_url", value)


@pulumi.type_token("acme:index/registration:Registration")
class Registration(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_key_algorithm: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_ecdsa_curve: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_pem: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_rsa_bits: Optional[pulumi.Input[_builtins.int]] = None,
                 email_address: Optional[pulumi.Input[_builtins.str]] = None,
                 external_account_binding: Optional[pulumi.Input[Union['RegistrationExternalAccountBindingArgs', 'RegistrationExternalAccountBindingArgsDict']]] = None,
                 __props__=None):
        """
        ## # Registration

        The `Registration` resource can be used to create and manage accounts on an
        ACME server. Once registered, the same private key that has been used for
        registration can be used to request authorizations for certificates.

        > This resource is named `Registration` for historical reasons - in the
        ACME v1 spec, a _registration_ referred to the account entity.  This resource
        name is stable and there are no plans to change it.

        > Keep in mind that when using this resource along with
        [`Certificate`][resource-certificate] within the same configuration, a
        change in the provider-level `server_url` (example: from the Let's Encrypt
        staging to production environment) within the same Terraform state will result
        in a resource failure, as Terraform will attempt to look for the account in the
        wrong CA. Consider different workspaces per environment, and/or using [multiple
        provider instances][multiple-provider-instances].

        [multiple-provider-instances]: https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations
        [resource-certificate]: ./certificate.md

        ## Example

        ### Basic Example

        The following is the most basic example. In this case, the account private key
        is managed for you.

        ```python
        import pulumi
        import pulumiverse_acme as acme

        reg = acme.Registration("reg")
        ```

        ### Using a Pre-Existing Private Key

        The following creates an account off of a private key generated with the
        [`tls_private_key`][resource-tls-private-key] resource.

        [resource-tls-private-key]: https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key

        ```python
        import pulumi
        import pulumi_tls as tls
        import pulumiverse_acme as acme

        private_key = tls.index.PrivateKey("private_key", algorithm=RSA)
        reg = acme.Registration("reg", account_key_pem=private_key["privateKeyPem"])
        ```

        #### Argument Reference

        > **NOTE:** All arguments in `Registration` force a new resource if
        changed.

        The resource takes the following arguments:

        * `account_key_pem` (Optional) - The private key used to identify the account.
          If not provided, the key will be generated according to the
          `account_key_algorithm`, `account_key_ecdsa_curve`, and
          `account_key_rsa_bits` settings.
        * `account_key_algorithm` (Optional) - The algorithm to use for the private key
          when generating from scratch. Supported settings: `RSA` and `EDCSA`. Default
          settings: `ECDSA`.
        * `account_key_ecdsa_curve` (Optional) - ECDSA curve to use for ECDSA key
          types. Supported settings: `P256` and `P384`. Default: `P384`.
        * `account_key_rsa_bits` (Optional) - The key length to use for RSA key types.
          Supported settings: `2048`, `3072`, and `4096`. Default: `4096`.
        * `email_address` (Optional) - The contact email address for the account.

        > Note that Let's Encrypt no longer sends expiry emails, and only uses this
        field for possible email list onboarding (see
        <https://letsencrypt.org/2025/06/26/expiration-notification-service-has-ended>).
        As such, it is not recommended to set this field when using Let's Encrypt.
        Other CAs may or may not require this field - consult the documentation of the
        CA you are using in this case.

        * `external_account_binding` (Optional) - An external account binding for the
          registration, usually used to link the registration with an account in a
          commercial CA. Sub-options are:
            - `key_id` (Required): The key ID for the external account binding.
            - `hmac_base64` (Required): The base64-encoded message authentication code
              for the external account binding.

        #### Attribute Reference

        The following attributes are exported:

        * `id`: The original full URL of the account.
        * `account_key_pem`: The private key used to identify the account (will be
          generated if not provided).
        * `registration_url`: The current full URL of the account.

        > `id` and `registration_url` will usually be the same and will usually only
        diverge when migrating protocols, ie: ACME v1 to v2.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[RegistrationArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## # Registration

        The `Registration` resource can be used to create and manage accounts on an
        ACME server. Once registered, the same private key that has been used for
        registration can be used to request authorizations for certificates.

        > This resource is named `Registration` for historical reasons - in the
        ACME v1 spec, a _registration_ referred to the account entity.  This resource
        name is stable and there are no plans to change it.

        > Keep in mind that when using this resource along with
        [`Certificate`][resource-certificate] within the same configuration, a
        change in the provider-level `server_url` (example: from the Let's Encrypt
        staging to production environment) within the same Terraform state will result
        in a resource failure, as Terraform will attempt to look for the account in the
        wrong CA. Consider different workspaces per environment, and/or using [multiple
        provider instances][multiple-provider-instances].

        [multiple-provider-instances]: https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations
        [resource-certificate]: ./certificate.md

        ## Example

        ### Basic Example

        The following is the most basic example. In this case, the account private key
        is managed for you.

        ```python
        import pulumi
        import pulumiverse_acme as acme

        reg = acme.Registration("reg")
        ```

        ### Using a Pre-Existing Private Key

        The following creates an account off of a private key generated with the
        [`tls_private_key`][resource-tls-private-key] resource.

        [resource-tls-private-key]: https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key

        ```python
        import pulumi
        import pulumi_tls as tls
        import pulumiverse_acme as acme

        private_key = tls.index.PrivateKey("private_key", algorithm=RSA)
        reg = acme.Registration("reg", account_key_pem=private_key["privateKeyPem"])
        ```

        #### Argument Reference

        > **NOTE:** All arguments in `Registration` force a new resource if
        changed.

        The resource takes the following arguments:

        * `account_key_pem` (Optional) - The private key used to identify the account.
          If not provided, the key will be generated according to the
          `account_key_algorithm`, `account_key_ecdsa_curve`, and
          `account_key_rsa_bits` settings.
        * `account_key_algorithm` (Optional) - The algorithm to use for the private key
          when generating from scratch. Supported settings: `RSA` and `EDCSA`. Default
          settings: `ECDSA`.
        * `account_key_ecdsa_curve` (Optional) - ECDSA curve to use for ECDSA key
          types. Supported settings: `P256` and `P384`. Default: `P384`.
        * `account_key_rsa_bits` (Optional) - The key length to use for RSA key types.
          Supported settings: `2048`, `3072`, and `4096`. Default: `4096`.
        * `email_address` (Optional) - The contact email address for the account.

        > Note that Let's Encrypt no longer sends expiry emails, and only uses this
        field for possible email list onboarding (see
        <https://letsencrypt.org/2025/06/26/expiration-notification-service-has-ended>).
        As such, it is not recommended to set this field when using Let's Encrypt.
        Other CAs may or may not require this field - consult the documentation of the
        CA you are using in this case.

        * `external_account_binding` (Optional) - An external account binding for the
          registration, usually used to link the registration with an account in a
          commercial CA. Sub-options are:
            - `key_id` (Required): The key ID for the external account binding.
            - `hmac_base64` (Required): The base64-encoded message authentication code
              for the external account binding.

        #### Attribute Reference

        The following attributes are exported:

        * `id`: The original full URL of the account.
        * `account_key_pem`: The private key used to identify the account (will be
          generated if not provided).
        * `registration_url`: The current full URL of the account.

        > `id` and `registration_url` will usually be the same and will usually only
        diverge when migrating protocols, ie: ACME v1 to v2.


        :param str resource_name: The name of the resource.
        :param RegistrationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RegistrationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_key_algorithm: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_ecdsa_curve: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_pem: Optional[pulumi.Input[_builtins.str]] = None,
                 account_key_rsa_bits: Optional[pulumi.Input[_builtins.int]] = None,
                 email_address: Optional[pulumi.Input[_builtins.str]] = None,
                 external_account_binding: Optional[pulumi.Input[Union['RegistrationExternalAccountBindingArgs', 'RegistrationExternalAccountBindingArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RegistrationArgs.__new__(RegistrationArgs)

            __props__.__dict__["account_key_algorithm"] = account_key_algorithm
            __props__.__dict__["account_key_ecdsa_curve"] = account_key_ecdsa_curve
            __props__.__dict__["account_key_pem"] = None if account_key_pem is None else pulumi.Output.secret(account_key_pem)
            __props__.__dict__["account_key_rsa_bits"] = account_key_rsa_bits
            __props__.__dict__["email_address"] = email_address
            __props__.__dict__["external_account_binding"] = external_account_binding
            __props__.__dict__["registration_url"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["accountKeyPem"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Registration, __self__).__init__(
            'acme:index/registration:Registration',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_key_algorithm: Optional[pulumi.Input[_builtins.str]] = None,
            account_key_ecdsa_curve: Optional[pulumi.Input[_builtins.str]] = None,
            account_key_pem: Optional[pulumi.Input[_builtins.str]] = None,
            account_key_rsa_bits: Optional[pulumi.Input[_builtins.int]] = None,
            email_address: Optional[pulumi.Input[_builtins.str]] = None,
            external_account_binding: Optional[pulumi.Input[Union['RegistrationExternalAccountBindingArgs', 'RegistrationExternalAccountBindingArgsDict']]] = None,
            registration_url: Optional[pulumi.Input[_builtins.str]] = None) -> 'Registration':
        """
        Get an existing Registration resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RegistrationState.__new__(_RegistrationState)

        __props__.__dict__["account_key_algorithm"] = account_key_algorithm
        __props__.__dict__["account_key_ecdsa_curve"] = account_key_ecdsa_curve
        __props__.__dict__["account_key_pem"] = account_key_pem
        __props__.__dict__["account_key_rsa_bits"] = account_key_rsa_bits
        __props__.__dict__["email_address"] = email_address
        __props__.__dict__["external_account_binding"] = external_account_binding
        __props__.__dict__["registration_url"] = registration_url
        return Registration(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountKeyAlgorithm")
    def account_key_algorithm(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "account_key_algorithm")

    @_builtins.property
    @pulumi.getter(name="accountKeyEcdsaCurve")
    def account_key_ecdsa_curve(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "account_key_ecdsa_curve")

    @_builtins.property
    @pulumi.getter(name="accountKeyPem")
    def account_key_pem(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "account_key_pem")

    @_builtins.property
    @pulumi.getter(name="accountKeyRsaBits")
    def account_key_rsa_bits(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "account_key_rsa_bits")

    @_builtins.property
    @pulumi.getter(name="emailAddress")
    def email_address(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "email_address")

    @_builtins.property
    @pulumi.getter(name="externalAccountBinding")
    def external_account_binding(self) -> pulumi.Output[Optional['outputs.RegistrationExternalAccountBinding']]:
        return pulumi.get(self, "external_account_binding")

    @_builtins.property
    @pulumi.getter(name="registrationUrl")
    def registration_url(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "registration_url")

