provider: acme
organization: pulumiverse
major-version: 1
providerDefaultBranch: main
upstreamProviderOrg: vancluever
publishRegistry: false
enableAutoRelease: false
languages:
  - dotnet
  - go
  - nodejs
  - python
