// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Acme
{
    /// <summary>
    /// ## # acme.Registration
    /// 
    /// The `acme.Registration` resource can be used to create and manage accounts on an
    /// ACME server. Once registered, the same private key that has been used for
    /// registration can be used to request authorizations for certificates.
    /// 
    /// &gt; This resource is named `acme.Registration` for historical reasons - in the
    /// ACME v1 spec, a _registration_ referred to the account entity.  This resource
    /// name is stable and there are no plans to change it.
    /// 
    /// &gt; Keep in mind that when using this resource along with
    /// [`acme.Certificate`][resource-certificate] within the same configuration, a
    /// change in the provider-level `ServerUrl` (example: from the Let's Encrypt
    /// staging to production environment) within the same Terraform state will result
    /// in a resource failure, as Terraform will attempt to look for the account in the
    /// wrong CA. Consider different workspaces per environment, and/or using [multiple
    /// provider instances][multiple-provider-instances].
    /// 
    /// [multiple-provider-instances]: https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations
    /// [resource-certificate]: ./certificate.md
    /// 
    /// ## Example
    /// 
    /// ### Basic Example
    /// 
    /// The following is the most basic example, supplying only a contact email address
    /// to the resource.
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Acme = Pulumiverse.Acme;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var reg = new Acme.Registration("reg", new()
    ///     {
    ///         EmailAddress = "nobody@example.com",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Using a Pre-Existing Private Key
    /// 
    /// The following creates an account off of a private key generated with the
    /// [`TlsPrivateKey`][resource-tls-private-key] resource.
    /// 
    /// [resource-tls-private-key]: https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Acme = Pulumiverse.Acme;
    /// using Tls = Pulumi.Tls;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var privateKey = new Tls.Index.PrivateKey("private_key", new()
    ///     {
    ///         Algorithm = "RSA",
    ///     });
    /// 
    ///     var reg = new Acme.Registration("reg", new()
    ///     {
    ///         AccountKeyPem = privateKey.PrivateKeyPem,
    ///         EmailAddress = "nobody@example.com",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// #### Argument Reference
    /// 
    /// &gt; **NOTE:** All arguments in `acme.Registration` force a new resource if
    /// changed.
    /// 
    /// The resource takes the following arguments:
    /// 
    /// * `AccountKeyPem` (Optional) - The private key used to identify the account.
    ///   If not provided, the key will be generated according to the
    ///   `AccountKeyAlgorithm`, `AccountKeyEcdsaCurve`, and
    ///   `AccountKeyRsaBits` settings.
    /// * `AccountKeyAlgorithm` (Optional) - The algorithm to use for the private key
    ///   when generating from scratch. Supported settings: `RSA` and `EDCSA`. Default
    ///   settings: `ECDSA`.
    /// * `AccountKeyEcdsaCurve` (Optional) - ECDSA curve to use for ECDSA key
    ///   types. Supported settings: `P256` and `P384`. Default: `P384`.
    /// * `AccountKeyRsaBits` (Optional) - The key length to use for RSA key types.
    ///   Supported settings: `2048`, `3072`, and `4096`. Default: `4096`.
    /// * `EmailAddress` (Required) - The contact email address for the account.
    /// * `ExternalAccountBinding` (Optional) - An external account binding for the
    ///   registration, usually used to link the registration with an account in a
    ///   commercial CA. Sub-options are:
    ///     - `KeyId` (Required): The key ID for the external account binding.
    ///     - `HmacBase64` (Required): The base64-encoded message authentication code
    ///       for the external account binding.
    /// 
    /// #### Attribute Reference
    /// 
    /// The following attributes are exported:
    /// 
    /// * `Id`: The original full URL of the account.
    /// * `AccountKeyPem`: The private key used to identify the account (will be
    ///   generated if not provided).
    /// * `RegistrationUrl`: The current full URL of the account.
    /// 
    /// &gt; `Id` and `RegistrationUrl` will usually be the same and will usually only
    /// diverge when migrating protocols, ie: ACME v1 to v2.
    /// </summary>
    [AcmeResourceType("acme:index/registration:Registration")]
    public partial class Registration : global::Pulumi.CustomResource
    {
        [Output("accountKeyAlgorithm")]
        public Output<string?> AccountKeyAlgorithm { get; private set; } = null!;

        [Output("accountKeyEcdsaCurve")]
        public Output<string?> AccountKeyEcdsaCurve { get; private set; } = null!;

        [Output("accountKeyPem")]
        public Output<string> AccountKeyPem { get; private set; } = null!;

        [Output("accountKeyRsaBits")]
        public Output<int?> AccountKeyRsaBits { get; private set; } = null!;

        [Output("emailAddress")]
        public Output<string> EmailAddress { get; private set; } = null!;

        [Output("externalAccountBinding")]
        public Output<Outputs.RegistrationExternalAccountBinding?> ExternalAccountBinding { get; private set; } = null!;

        [Output("registrationUrl")]
        public Output<string> RegistrationUrl { get; private set; } = null!;


        /// <summary>
        /// Create a Registration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Registration(string name, RegistrationArgs args, CustomResourceOptions? options = null)
            : base("acme:index/registration:Registration", name, args ?? new RegistrationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Registration(string name, Input<string> id, RegistrationState? state = null, CustomResourceOptions? options = null)
            : base("acme:index/registration:Registration", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse/pulumi-acme",
                AdditionalSecretOutputs =
                {
                    "accountKeyPem",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Registration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Registration Get(string name, Input<string> id, RegistrationState? state = null, CustomResourceOptions? options = null)
        {
            return new Registration(name, id, state, options);
        }
    }

    public sealed class RegistrationArgs : global::Pulumi.ResourceArgs
    {
        [Input("accountKeyAlgorithm")]
        public Input<string>? AccountKeyAlgorithm { get; set; }

        [Input("accountKeyEcdsaCurve")]
        public Input<string>? AccountKeyEcdsaCurve { get; set; }

        [Input("accountKeyPem")]
        private Input<string>? _accountKeyPem;
        public Input<string>? AccountKeyPem
        {
            get => _accountKeyPem;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accountKeyPem = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("accountKeyRsaBits")]
        public Input<int>? AccountKeyRsaBits { get; set; }

        [Input("emailAddress", required: true)]
        public Input<string> EmailAddress { get; set; } = null!;

        [Input("externalAccountBinding")]
        public Input<Inputs.RegistrationExternalAccountBindingArgs>? ExternalAccountBinding { get; set; }

        public RegistrationArgs()
        {
        }
        public static new RegistrationArgs Empty => new RegistrationArgs();
    }

    public sealed class RegistrationState : global::Pulumi.ResourceArgs
    {
        [Input("accountKeyAlgorithm")]
        public Input<string>? AccountKeyAlgorithm { get; set; }

        [Input("accountKeyEcdsaCurve")]
        public Input<string>? AccountKeyEcdsaCurve { get; set; }

        [Input("accountKeyPem")]
        private Input<string>? _accountKeyPem;
        public Input<string>? AccountKeyPem
        {
            get => _accountKeyPem;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accountKeyPem = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("accountKeyRsaBits")]
        public Input<int>? AccountKeyRsaBits { get; set; }

        [Input("emailAddress")]
        public Input<string>? EmailAddress { get; set; }

        [Input("externalAccountBinding")]
        public Input<Inputs.RegistrationExternalAccountBindingGetArgs>? ExternalAccountBinding { get; set; }

        [Input("registrationUrl")]
        public Input<string>? RegistrationUrl { get; set; }

        public RegistrationState()
        {
        }
        public static new RegistrationState Empty => new RegistrationState();
    }
}
