// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Acme.Outputs
{

    [OutputType]
    public sealed class CertificateDnsChallenge
    {
        public readonly ImmutableDictionary<string, string>? Config;
        public readonly ImmutableArray<string> MatchDomains;
        public readonly string Provider;

        [OutputConstructor]
        private CertificateDnsChallenge(
            ImmutableDictionary<string, string>? config,

            ImmutableArray<string> matchDomains,

            string provider)
        {
            Config = config;
            MatchDomains = matchDomains;
            Provider = provider;
        }
    }
}
