// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Acme.Outputs
{

    [OutputType]
    public sealed class CertificateHttpWebrootChallenge
    {
        /// <summary>
        /// The directory to publish the record to.
        /// </summary>
        public readonly string Directory;

        [OutputConstructor]
        private CertificateHttpWebrootChallenge(string directory)
        {
            Directory = directory;
        }
    }
}
