// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CertificateDnsChallenge {
    config?: pulumi.Input<{[key: string]: any}>;
    provider: pulumi.Input<string>;
}

export interface CertificateHttpChallenge {
    port?: pulumi.Input<number>;
    proxyHeader?: pulumi.Input<string>;
}

export interface CertificateHttpMemcachedChallenge {
    hosts: pulumi.Input<pulumi.Input<string>[]>;
}

export interface CertificateHttpWebrootChallenge {
    directory: pulumi.Input<string>;
}

export interface CertificateTlsChallenge {
    port?: pulumi.Input<number>;
}

export interface RegistrationExternalAccountBinding {
    hmacBase64: pulumi.Input<string>;
    keyId: pulumi.Input<string>;
}
