// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface CertificateDnsChallenge {
    config?: {[key: string]: any};
    provider: string;
}

export interface CertificateHttpChallenge {
    port?: number;
    proxyHeader?: string;
}

export interface CertificateHttpMemcachedChallenge {
    hosts: string[];
}

export interface CertificateHttpWebrootChallenge {
    directory: string;
}

export interface CertificateTlsChallenge {
    port?: number;
}

export interface RegistrationExternalAccountBinding {
    hmacBase64: string;
    keyId: string;
}

