// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Acme.Inputs
{

    public sealed class CertificateHttpChallengeArgs : global::Pulumi.ResourceArgs
    {
        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("proxyHeader")]
        public Input<string>? ProxyHeader { get; set; }

        public CertificateHttpChallengeArgs()
        {
        }
        public static new CertificateHttpChallengeArgs Empty => new CertificateHttpChallengeArgs();
    }
}
