// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## # acme.Registration
 *
 * The `acme.Registration` resource can be used to create and manage accounts on an
 * ACME server. Once registered, the same private key that has been used for
 * registration can be used to request authorizations for certificates.
 *
 * > This resource is named `acme.Registration` for historical reasons - in the
 * ACME v1 spec, a _registration_ referred to the account entity.  This resource
 * name is stable and there are no plans to change it.
 *
 * > Keep in mind that when using this resource along with
 * [`acme.Certificate`][resource-certificate] within the same configuration, a
 * change in the provider-level `serverUrl` (example: from the Let's Encrypt
 * staging to production environment) within the same Terraform state will result
 * in a resource failure, as Terraform will attempt to look for the account in the
 * wrong CA. Consider different workspaces per environment, and/or using [multiple
 * provider instances][multiple-provider-instances].
 *
 * [multiple-provider-instances]: https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations
 * [resource-certificate]: ./certificate.md
 *
 * ## Example
 *
 * ### Basic Example
 *
 * The following is the most basic example, supplying only a contact email address
 * to the resource.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as acme from "@pulumiverse/acme";
 *
 * const reg = new acme.Registration("reg", {emailAddress: "nobody@example.com"});
 * ```
 *
 * ### Using a Pre-Existing Private Key
 *
 * The following creates an account off of a private key generated with the
 * [`tlsPrivateKey`][resource-tls-private-key] resource.
 *
 * [resource-tls-private-key]: https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as acme from "@pulumiverse/acme";
 * import * as tls from "@pulumi/tls";
 *
 * const privateKey = new tls.index.PrivateKey("private_key", {algorithm: "RSA"});
 * const reg = new acme.Registration("reg", {
 *     accountKeyPem: privateKey.privateKeyPem,
 *     emailAddress: "nobody@example.com",
 * });
 * ```
 *
 * #### Argument Reference
 *
 * > **NOTE:** All arguments in `acme.Registration` force a new resource if
 * changed.
 *
 * The resource takes the following arguments:
 *
 * * `accountKeyPem` (Optional) - The private key used to identify the account.
 *   If not provided, the key will be generated according to the
 *   `accountKeyAlgorithm`, `accountKeyEcdsaCurve`, and
 *   `accountKeyRsaBits` settings.
 * * `accountKeyAlgorithm` (Optional) - The algorithm to use for the private key
 *   when generating from scratch. Supported settings: `RSA` and `EDCSA`. Default
 *   settings: `ECDSA`.
 * * `accountKeyEcdsaCurve` (Optional) - ECDSA curve to use for ECDSA key
 *   types. Supported settings: `P256` and `P384`. Default: `P384`.
 * * `accountKeyRsaBits` (Optional) - The key length to use for RSA key types.
 *   Supported settings: `2048`, `3072`, and `4096`. Default: `4096`.
 * * `emailAddress` (Required) - The contact email address for the account.
 * * `externalAccountBinding` (Optional) - An external account binding for the
 *   registration, usually used to link the registration with an account in a
 *   commercial CA. Sub-options are:
 *     - `keyId` (Required): The key ID for the external account binding.
 *     - `hmacBase64` (Required): The base64-encoded message authentication code
 *       for the external account binding.
 *
 * #### Attribute Reference
 *
 * The following attributes are exported:
 *
 * * `id`: The original full URL of the account.
 * * `accountKeyPem`: The private key used to identify the account (will be
 *   generated if not provided).
 * * `registrationUrl`: The current full URL of the account.
 *
 * > `id` and `registrationUrl` will usually be the same and will usually only
 * diverge when migrating protocols, ie: ACME v1 to v2.
 */
export class Registration extends pulumi.CustomResource {
    /**
     * Get an existing Registration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RegistrationState, opts?: pulumi.CustomResourceOptions): Registration {
        return new Registration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'acme:index/registration:Registration';

    /**
     * Returns true if the given object is an instance of Registration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Registration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Registration.__pulumiType;
    }

    declare public readonly accountKeyAlgorithm: pulumi.Output<string | undefined>;
    declare public readonly accountKeyEcdsaCurve: pulumi.Output<string | undefined>;
    declare public readonly accountKeyPem: pulumi.Output<string>;
    declare public readonly accountKeyRsaBits: pulumi.Output<number | undefined>;
    declare public readonly emailAddress: pulumi.Output<string>;
    declare public readonly externalAccountBinding: pulumi.Output<outputs.RegistrationExternalAccountBinding | undefined>;
    declare public /*out*/ readonly registrationUrl: pulumi.Output<string>;

    /**
     * Create a Registration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RegistrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RegistrationArgs | RegistrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RegistrationState | undefined;
            resourceInputs["accountKeyAlgorithm"] = state?.accountKeyAlgorithm;
            resourceInputs["accountKeyEcdsaCurve"] = state?.accountKeyEcdsaCurve;
            resourceInputs["accountKeyPem"] = state?.accountKeyPem;
            resourceInputs["accountKeyRsaBits"] = state?.accountKeyRsaBits;
            resourceInputs["emailAddress"] = state?.emailAddress;
            resourceInputs["externalAccountBinding"] = state?.externalAccountBinding;
            resourceInputs["registrationUrl"] = state?.registrationUrl;
        } else {
            const args = argsOrState as RegistrationArgs | undefined;
            if (args?.emailAddress === undefined && !opts.urn) {
                throw new Error("Missing required property 'emailAddress'");
            }
            resourceInputs["accountKeyAlgorithm"] = args?.accountKeyAlgorithm;
            resourceInputs["accountKeyEcdsaCurve"] = args?.accountKeyEcdsaCurve;
            resourceInputs["accountKeyPem"] = args?.accountKeyPem ? pulumi.secret(args.accountKeyPem) : undefined;
            resourceInputs["accountKeyRsaBits"] = args?.accountKeyRsaBits;
            resourceInputs["emailAddress"] = args?.emailAddress;
            resourceInputs["externalAccountBinding"] = args?.externalAccountBinding;
            resourceInputs["registrationUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["accountKeyPem"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Registration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Registration resources.
 */
export interface RegistrationState {
    accountKeyAlgorithm?: pulumi.Input<string>;
    accountKeyEcdsaCurve?: pulumi.Input<string>;
    accountKeyPem?: pulumi.Input<string>;
    accountKeyRsaBits?: pulumi.Input<number>;
    emailAddress?: pulumi.Input<string>;
    externalAccountBinding?: pulumi.Input<inputs.RegistrationExternalAccountBinding>;
    registrationUrl?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Registration resource.
 */
export interface RegistrationArgs {
    accountKeyAlgorithm?: pulumi.Input<string>;
    accountKeyEcdsaCurve?: pulumi.Input<string>;
    accountKeyPem?: pulumi.Input<string>;
    accountKeyRsaBits?: pulumi.Input<number>;
    emailAddress: pulumi.Input<string>;
    externalAccountBinding?: pulumi.Input<inputs.RegistrationExternalAccountBinding>;
}
